// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyOVYuulP0zSnrNsNDR-204Y14Gqy5BRA',
    appId: '1:1056875680430:web:fd45f8bb448cddefbdd33f',
    messagingSenderId: '1056875680430',
    projectId: 'stethapp',
    authDomain: 'stethapp.firebaseapp.com',
    storageBucket: 'stethapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAZtGHzQhvxXjwnXlXo3Y2od-3mMPoTdY',
    appId: '1:1056875680430:android:bffa1a9dc28cc2abbdd33f',
    messagingSenderId: '1056875680430',
    projectId: 'stethapp',
    storageBucket: 'stethapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAD9yMIoSFLOiVcq1QZzNniL9iN0tVHVo',
    appId: '1:1056875680430:ios:c9a05570a1253098bdd33f',
    messagingSenderId: '1056875680430',
    projectId: 'stethapp',
    storageBucket: 'stethapp.firebasestorage.app',
    iosBundleId: 'com.example.stethoscope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAD9yMIoSFLOiVcq1QZzNniL9iN0tVHVo',
    appId: '1:1056875680430:ios:c9a05570a1253098bdd33f',
    messagingSenderId: '1056875680430',
    projectId: 'stethapp',
    storageBucket: 'stethapp.firebasestorage.app',
    iosBundleId: 'com.example.stethoscope',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyOVYuulP0zSnrNsNDR-204Y14Gqy5BRA',
    appId: '1:1056875680430:web:70fd8b92dab056a0bdd33f',
    messagingSenderId: '1056875680430',
    projectId: 'stethapp',
    authDomain: 'stethapp.firebaseapp.com',
    storageBucket: 'stethapp.firebasestorage.app',
  );
}
